// Autogenerated file, don't edit anything
#pragma once

#include <incbin.h>

#define SDL_Incbin(NAME) \
    SDL_RWFromConstMem( \
        INCBIN_CONCATENATE( \
            INCBIN_CONCATENATE(INCBIN_PREFIX, NAME), \
            INCBIN_STYLE_IDENT(DATA) \
        ), \
        INCBIN_CONCATENATE( \
            INCBIN_CONCATENATE(INCBIN_PREFIX, NAME), \
            INCBIN_STYLE_IDENT(SIZE) \
        ) \
    )

#define FONT_FONT_TTF FONT_FONT_TTF
#define ICON_BMP ICON_BMP
#define ICON_ICO ICON_ICO

INCBIN_EXTERN(FONT_FONT_TTF);
INCBIN_EXTERN(ICON_BMP);
INCBIN_EXTERN(ICON_ICO);
